# 服务器配置
server:
  port: 8123
  servlet:
    context-path: /api

# Spring框架配置
spring:
  profiles:
    active: prod  # 激活生产环境配置
  # 应用配置
  application:
    name: domye-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dmoye_picture
    username:
    password:

  # ShardingSphere配置
  shardingsphere:
    # 数据源配置
    datasource:
      names: dmoye_picture
      dmoye_picture:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/dmoye_picture?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username:
        password:

    # 规则配置
    rules:
      sharding:
        # 分表配置
        tables:
          picture:
            actual-data-nodes: dmoye_picture.picture
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm

        # 分片算法配置
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.domye.picture.manager.sharding.PictureShardingAlgorithm

    # 属性配置
    props:
      sql-show: true

  # Servlet配置
  servlet:
    multipart:
      max-file-size: 10MB

  # Redis配置
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    enable-sql-runner: true
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# Knife4j配置
knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    version: v1.0
    group:
      test1:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.domye.picture.controller

# 腾讯云COS配置
#cos:
#  client:
#    host:
#    secretId:
#    secretKey:
#    region:
#    bucket:
