# 服务器配置
server:
  port: 8123
  servlet:
    context-path: /api

# Spring框架配置
spring:
  profiles:
    active: local  # 激活生产环境配置
  # 应用配置
  application:
    name: domye-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/domye_picture?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}

  # Servlet配置
  servlet:
    multipart:
      max-file-size: 10MB

  # Redis配置
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 63793
      timeout: 5000
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    enable-sql-runner: true
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# Knife4j配置
knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    version: v1.0
    group:
      test1:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.domye.picture.controller

# 腾讯云COS配置
#cos:
#  client:
#    host:
#    secretId:
#    secretKey:
#    region:
#    bucket:
